apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketNotification
metadata:
  name: bucket-kafka-notification
spec:
  forProvider:
    bucket: <YOUR_BUCKET_NAME>
    topic:
      - id: kafka-all-events
        events:
          - "s3:ObjectCreated:*"
          - "s3:ObjectRemoved:*"
        topicArn: "kafka-notif-connection/connect.json"
    region: us-east-1
  providerConfigRef:
    name: noobaa-s3
