apiVersion: s3.aws.upbound.io/v1beta2
kind: BucketLifecycleConfiguration
metadata:
  name: bucket-lifecycle-expiration
spec:
  forProvider:
    bucket: <YOUR_BUCKET_NAME>
    rule:
      # Change "days" to match your retention requirements (7 is a placeholder).
      - id: auto-expire-objects
        status: Enabled
        filter:
          - prefix: ""
        expiration:
          - days: 7
    region: us-east-1
  providerConfigRef:
    name: noobaa-s3
